### ISSUE TITLE
Get script packs working

### ISSUE THREAD

**Issue by glennblock** [scriptcs-contrib/scriptcs-mef#2]
I am on this!

**Comment by laedit** [comment]
Thanks! :smiley:

**Comment by glennblock** [comment]
Working on it now.

**Comment by glennblock** [comment]
I see the problem. Stay tuned

**Comment by glennblock** [comment]
It's working....I am going to send you an updated sample. The code to call the script pack resolver was not needed.

**Comment by glennblock** [comment]
I take that back it was needed. The issue was that the ScriptName property must be set to empty string on the builder. You'll see it in my PR. Here's proof showing the Logger ScriptPack working :-)

![screen shot 2015-03-26 at 12 56 26 am](https://cloud.githubusercontent.com/assets/141124/6842274/050ac7a8-d353-11e4-9846-5bd50c2f8394.png)

PR is ready....
