### ISSUE TITLE
Error when running sample

### ISSUE THREAD

**Issue by glennblock** [scriptcs-contrib/scriptcs-mef#3]
```
An unhandled exception of type 'System.IO.DirectoryNotFoundException' occurred in ScriptCs.ComponentModel.Composition.dll

Additional information: Scripts folder: 'C:\src\scriptcs-mef\sample\ScriptCompositionSample\bin\Debug\Scripts' does not exist
```

**Comment by laedit** [comment]
Yeah, this is because the specified folder "Scripts" is missing from the current folder.
Do you think if the folder doesn't exists the catalog should just log a warning and not throw an exception?
If not I will just change the sample to automatically creates the folder if needed.

**Comment by glennblock** [comment]
I think your sample should be properly set up ;-).

I'll send a small PR, I have that working

**Comment by glennblock** [comment]
You don't need code to do that, you can just have the sample include a folder which is deployed to bin. My PR does this.
