### ISSUE TITLE
Custom FileSystem fails

### ISSUE THREAD

**Issue by beolutz** [scriptcs-contrib/scriptcs-mef#9]
Could you change the following line of the CreateScriptServices method:
``` cs
scriptServicesBuilder.Overrides[typeof(IFileSystem)] = _options.FileSystem;
```
to
``` cs
initializationServices.Overrides[typeof(IFileSystem)] = _options.FileSystem;
```
because the `LoadModules` method of the `ScriptServicesBuilder` calls `InitializationServices.GetFileSystem()`
Thanks

**Comment by laedit** [comment]
After some investigation it seems that both 
``` cs
new InitializationServices(logProvider, new Dictionary<Type, object> { { typeof(IFileSystem), _options.FileSystem } });
```
 and 
``` cs
scriptServicesBuilder.Overrides[typeof(IFileSystem)] = _options.FileSystem;
```
 are needed to use a custom `IFileSystem` in hosting scenarios, but the targeted script file need to exist on the system.

@glennblock is this correct or am I doing something wrong?

**Comment by beolutz** [comment]
#11
